### ISSUE TITLE
[SUGGESTION] Stick to brick/part that you are standing on like ;stick cmd but for parts

### ISSUE THREAD

**Issue by hxlpm3** [CMD-X/CMD-X#19]
Please read!!!

There is a ;stick cmd for players but not for parts. I would like one for parts so that I can stand on airplanes/cars/etc. and not fall down. It will basically weld my foot/player onto the part completely so that when the part moves, I move along with it. 

Extremely useful in cases where there is a rolling ball and you walk up to it to glue yourself onto the ball so you roll along with the ball.

I know there's a wallrun/gravcontroller script but that's completely different. I actually want to be glued to a part basically to stand on aircrafts/etc. without falling!!!

CMD USAGE: ;glue and ;unglue

**Comment by peckingduck101** [comment]
nice cock bro
