### ISSUE TITLE
The disableplayer command doesn't disable chat bubbles from the target player, as well as their face decal.

### ISSUE THREAD

**Issue by Walter-X** [CMD-X/CMD-X#27]
![RobloxPlayerBeta_9APN1Pcp8x](https://user-images.githubusercontent.com/66207878/86934492-c019bc80-c109-11ea-9e87-a6cc9065cedc.png)

**Comment by CMD-X** [comment]
You can block or mute the user you disable using Roblox, although I will fix the face decal issue.
