### ISSUE TITLE
Chatframe command only works with message bubbles, not the actual chat

### ISSUE THREAD

**Issue by Walter-X** [CMD-X/CMD-X#28]
Attached below are 2 images. One of them depicts a playing chatting normally, and the other depicts a fake message created via chatframe. Generating a fake massage in the chat GUI as well would be useful for games which normally do not feature chat bubbles.

![RobloxPlayerBeta_JUb00HaLwS](https://user-images.githubusercontent.com/66207878/86936604-3d463100-c10c-11ea-9990-01d425812571.png)
![RobloxPlayerBeta_uQnXat4pJH](https://user-images.githubusercontent.com/66207878/86936615-40d9b800-c10c-11ea-99a4-2fb56a57aa53.png)

**Comment by knifemarks** [comment]
this is not an issue but we will consider it as a suggestion
