### ISSUE TITLE
CMD-X doesnt work on krnl

### ISSUE THREAD

**Issue by ZWRh3** [CMD-X/CMD-X#3]
well the title is in the title it error like this:

1590652814.07912,38b8,6 Error: :11833: attempt to call a nil value
    Stack Begin
    Script '', Line 11833
    Script '', Line 1
    Stack End

**Comment by CMD-X** [comment]
I'll look into it, I'm gonna guess its just a KRNL issue?

**Comment by CMD-X** [comment]
Ok found the issue, looks like KRNL doesn't support a function inside of the depth pastebin. I'll load it into the command instead.

**Comment by CMD-X** [comment]
KRNL issue should be fixed, please take a check.

Thanks.

**Comment by enescaglayan** [comment]
cmd x add fixed label
