### ISSUE TITLE
Aimbot Hotkey

### ISSUE THREAD

**Issue by vAmaari** [CMD-X/CMD-X#32]
Could you make it so we can change the hot key for the aimbot cmd it works really we'll it's just in some games they already have the crtl left button in use.

**Comment by knifemarks** [comment]
.hotkeyaimbot

**Comment by YourTrashh** [comment]
yeah but isn't .hotkeyaimbot just enable and disable the Aimbot?

**Comment by LamSav** [comment]
anyone fiqure it out yet?
