### ISSUE TITLE
[SUGGESTION] Expansion for .animation

### ISSUE THREAD

**Issue by IzMend** [CMD-X/CMD-X#33]
I'm not exactly sure what limits .anim to playing roblox-only assets, but I think it would be a useful addition to support user-made animations as well as R15 animations for easy testing or just messing around ..

**Comment by CMD-X** [comment]
The reason for not allowing user made animations to play is made obvious as Roblox does not replicate them unless ran by the server.
Therefore it is NOT possible.
R15 animations have their own corresponding command called .emote (name) which you can pick from a list of official emotes from the catalog for free.
