### ISSUE TITLE
[SUGGESTION] animation scripts in gui

### ISSUE THREAD

**Issue by Ada64** [CMD-X/CMD-X#42]
i want animation scripts to be in the gui, you can get them from anywhere or make your own.
if you cant make buttons that execute the script, just make it so when the player presses it then it gives the animation script code
thank you

**Comment by CMD-X** [comment]
These are already commands that exist. (not in the way you mentioned it but similar)

.repanim (id) (speed) - Replicates an animation (R6)
.anim (id) (speed) - Use a verified animation (R6)
.emote (name) - Use a verified emote (R15)
.animspeed (speed) - Change animation speed (better with .loop)

**Comment by Ada64** [comment]
> These are already commands that exist. (not in the way you mentioned it but similar)
> 
> .repanim (id) (speed) - Replicates an animation (R6)
> .anim (id) (speed) - Use a verified animation (R6)
> .emote (name) - Use a verified emote (R15)
> .animspeed (speed) - Change animation speed (better with .loop)

i was guessing there was gonna be a gui in the new v2, guess not

**Comment by CMD-X** [comment]
There will be a new GUI in v2 for CMD-X.
