### ISSUE TITLE
Invis Issues

### ISSUE THREAD

**Issue by Exarmy** [CMD-X/CMD-X#43]
Firstly there is no Un Invis command which is annoying. Then I find that invis is broken in pretty much all games. Fix please

-Gort Worshiper

**Comment by CMD-X** [comment]
Thanks for your report, we will have a look into this for V2.

**Comment by xxhertz** [comment]
Uninvisible is not possible and if the invis does not work on the game then it must be patched on that specific game due to some custom behaviors. To make yourself visible again, refresh your character using .refresh
