### ISSUE TITLE
Choose to [SUGGESTION] change where the Aimbot locks on to

### ISSUE THREAD

**Issue by jOe5412** [CMD-X/CMD-X#44]
As of now aimbot only aims for the head and it would be great if it had a command to change what body part to lock on.. like aimlock chest, head, etc

**Comment by VanillaDeveloperRoom** [comment]
Yeah, this would be useful!

**Comment by CMD-X** [comment]
Thank you for your suggestion, this will be worked on and released in V2.

**Comment by CMD-X** [comment]
This has been finished and will be released in V2
