### ISSUE TITLE
antilag command once again does not work in arsenal

### ISSUE THREAD

**Issue by mawseed** [CMD-X/CMD-X#49]
When you join arsenal and try to use the antilag command, the game will not let you spawn in. Is there a fix for this? (the reason why im using it there is to trigger a glitch which turns your outfit pink/lavender-ish)

**Comment by CMD-X** [comment]
I'll see whats causing the problem.

It really shouldn't be doing this as anti-lag just messes with your games textures and non-important workspace objects.

Expect a fix in V2.
