### ISSUE TITLE
Fling doesnt work

### ISSUE THREAD

**Issue by zokanzin** [CMD-X/CMD-X#56]
It doesnt

**Comment by Curvn** [comment]
it does

**Comment by SirBaeconMan** [comment]
it does, but it depends on whether player collision is on in the game. if its off, it wont work.

**Comment by CMD-X** [comment]
Fling is working.

You need to make sure your character can collide with the other player.

A correct env for fling would be a game where Player-Collisions are on and the target is not No-Clipped and that target is not evading at high speeds.
