### ISSUE TITLE
[SUGGESTION] ClickTP Limit

### ISSUE THREAD

**Issue by zeltwood** [CMD-X/CMD-X#61]
Some games have limits to how far the player can move in a certain amount of time to prevent teleporting. 
ex; [Mortem Metallum](https://www.roblox.com/games/4169490976/Mortem-Metallum-Alpha?refPageId=09eadc28-c569-4697-8e0c-dfee82777cdc) doesn't let me teleport further than 41 studs (tested in-game with click tp and used f3x to make a 'ruler)

I could bypass this either by teleporting short distances within 41 studs, which proves very challenging.

Being able to set a limit would make this much easier. I tried programming my own limit for a clicktp script I found online but I don't know what I'm doing.

.clicktplimit 41   example of how it could be called

Thank you

**Comment by zeltwood** [comment]
[Here](https://scriptinghelpers.org/questions/29526/teleporting-character-script-with-a-limit-to-where-you-can-teleport) is a link that might help programming this limit

**Comment by CMD-X** [comment]
I will consider this in V2.
This has also brought a few more ideas to my attention, thank you.

**Comment by xxhertz** [comment]
will be pushed with next update
