### ISSUE TITLE
Just a bit of help

### ISSUE THREAD

**Issue by JustaFloatingEyeYT** [CMD-X/CMD-X#64]
I am a bit confused on how the "Viewserver" command works, also is there maybe a list of all commands and how to use them, some commands are hard to use and aren't fully explained in the CMDS list of CMD-X

**Comment by xxhertz** [comment]
If you could please provide an example of the commands you're mentioning I can fix their descriptions, thanks.

**Comment by JustaFloatingEyeYT** [comment]
Well, that was some time ago so I forgot which ones, but I did say "Viewserver" so that is one.

**Comment by xxhertz** [comment]
`["viewserver"] = "Allows you to see players in another server.",`
seems pretty descriptive to me, maybe it was changed since this issue was opened

**Comment by JustaFloatingEyeYT** [comment]
Yeah, also I forgot about this so sorry for the wait, I will close this issue now
