### ISSUE TITLE
Missing file extensions and mistyped directory name

### ISSUE THREAD

**Issue by benjysugi** [CMD-X/CMD-X#65]
You might wanna add the missing file extensions for the following files, since they seem to be missing.
- `CMD-X`
- `Source`
- `Version`
- `projects\AngularWalk`
- `projects\BackpackingAF`
- `projects\BadgeSniper`
- `projects\CMD-XNexusHand`
- `projects\CMD-XThemeCMDPROMPT`
- `projects\ForceStaus`
- `projects\HFFRoblox`
- `projects\InGameFlingForTB`
- `projects\PlayerStalkerV2`
- `projects\RBLXKeycodes`
- `projects\TaskbarBots`
- `projects\diagnoser`
- `projects\limsimautobuy`
- `projects\parkouresp`
- `projects\showonlineoffline`
- `projects\spotifypresence`
- `projects\tooltips`
- `projects\unfriendall`
- `projects\AlwaysDollhouse\Game`
- `projects\AlwaysDollhouse\Spectate`
- `projects\AlwaysDollhouse\TimePlayer`
- `projects\AlwaysDollhouse\TimeServer`
- All the files in `others\`

There is also a spelling mistake, `projects` is misspelt as `projetcs`

**Comment by xxhertz** [comment]
For the Source and CMD-X one, they can't have file extensions added as many MANY people depend on the link, including KRNL users who use CMD-X. As for the rest, they'll be renamed and fixed. Thanks for this, will be treated asap.
